# Generated by Django 5.0.3 on 2024-12-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
